### ISSUE TITLE
Sensors (domain sensor) as temperature.sensor

### ISSUE THREAD

**Issue by gd360** [tetele/hvac_group#31]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/tetele/hvac_group/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hello,

I just tried adding my first hvac_group. It seems that you can add an actual pure temperature sensor as the sensor of a group. Is this wanted behaviour?  I could add a thermostat (domain climate) but I have an sonoff sensor that runs under the domain "sensor".

kind regards
Gerhard

### Describe the solution you'd like

You can add a temperature sensor from domain sensor

### Describe alternatives you've considered

cant think of any

### Additional context

no context needed imo

**Comment by gd360** [comment]
Hallo,

thanks a lot for the fast help. I am still pretty new to this. 
Just to be sure, I wasnt able to add a generic sensor to the helper, as it limited to "climate" entity. 
But now I saw that there is a fork for an external temp sensor, so is this perhaps exactly what I wanted then?

**Comment by tetele** [comment]
Appologies, I forgot that I haven't merged that feature :) Since you're the first person to use the helper that I interact with, I have been on my own so far.

So, to answer your initial question, now that I understand it better: yes, there is support for temp `sensor`s and I've just merged them.

**Comment by tetele** [comment]
Fixed in #33

**Comment by gd360** [comment]
thank you!

**Comment by MasterDevwi** [comment]
Hi @tetele! Which device classes are supported? I've created a template sensor with the "temperature" device_class, but the UI isn't listing the sensor as one of the available options. Should I be specifying a different device_class?

**Comment by tetele** [comment]
@MasterDevwi it works for me with a template sensor with `device_class: temperature`, `state_class: measurement` and `unit_of_measurement: °C`. Could you paste the full list of attributes of your sensor (from dev tools)?

**Comment by MasterDevwi** [comment]
@tetele Thanks! Apparently I was missing the state_class. Once I added it it showed up.
