### ISSUE TITLE
Problem with air conditioning in multiple rooms

### ISSUE THREAD

**Issue by aantonelloborges** [tetele/hvac_group#51]
## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | America/Sao_Paulo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4929
Installed Version | 1.34.0
Stage | running
Available Repositories | 1385
Downloaded Repositories | 54

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 12, 2024 at 21:00
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-10.ui.nabu.casa
certificate_status | ready
instance_id | 3012c7b11c2a4c6e8aeb1c9f89ab4003
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 14.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), Home Assistant Google Drive Backup (0.112.1), go2rtc (1.8.5), Frigate (0.12.1), MQTT Explorer (browser-1.0.1), Spotify Connect (0.13.0), Glances (0.21.0), eWeLink Smart Home (1.4.3), ESPHome (2023.12.9), TasmoAdmin (0.29.1), Studio Code Server (5.15.0), Matter Server (5.0.4), Mosquitto broker (6.4.0), MariaDB (2.6.1), Zigbee2MQTT (1.35.1-1), Uptime Kuma (0.12.0), MQTT IO (0.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 36
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 30, 2023 at 01:00
-- | --
current_recorder_run | January 25, 2024 at 22:25
estimated_db_size | 752.97 MiB
database_engine | mysql
database_version | 11.1.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/tetele/hvac_group/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I can't enable my 4 multi-split Samsung Wind Free via Smart Things integration with the group card.

### Reproduction steps

1. Create a group with 4 cliamte air contitioner things
2. Enable the "Toggle heaters on or off depending on ambiental temperature" and "Toggle coolers on or off depending on ambiental temperature"
3. Submit
4. Open de helper and try to turn on but temperature is not enable to change

<img width="579" alt="image" src="https://github.com/tetele/hvac_group/assets/24994711/ce14ec9d-0359-4740-83f7-5894f14fce9d">

<img width="392" alt="image" src="https://github.com/tetele/hvac_group/assets/24994711/0eabe05b-e8ec-48fe-b155-b6873063d21a">

<img width="1519" alt="image" src="https://github.com/tetele/hvac_group/assets/24994711/59bd4dbd-ef7c-4a25-95e2-6453b327ee4b">

<img width="1210" alt="image" src="https://github.com/tetele/hvac_group/assets/24994711/55bacc67-1828-4e0d-9f43-526aaaa7ddb1">

### Debug logs

```text
n/a
```

**Comment by tetele** [comment]
Hi! Thanks for the report! Could you please also look for any errors in the HA core logs and add them here?

**Comment by tetele** [comment]
This may be related to #50 which was addressed. Could you try updating to 0.1.1 and let me know if it's fixed? If not, I will need the HA core logs. Thanks!

**Comment by aantonelloborges** [comment]
Hi tetele.

I updated to the new version and restarted HASS. However, as can be seen in the image below, the options for turning on the devices do not appear and consequently the temperature regulation is turned off.

I created a script that turns on all the devices at the same time and then I opened the HVAC Group and it continued showing the image below... as if everything was turned off.

<img width="445" alt="image" src="https://github.com/tetele/hvac_group/assets/24994711/04555603-aea5-4263-b1ed-1d9e70b2f086">


The only error in the logs reported to the HVAC Group is this:

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/utils/queue_manager.py:71
Integration: HACS (documentation, issues)
First occurred: 10:56:14 (1 occurrences)
Last logged: 10:56:14

<QueueManager> No commit found for the ref v4.9.0

**Comment by tetele** [comment]
I've almost completely re-written the integration and I'm hoping it's much more robust now. There's a [0.2.0-beta](https://github.com/tetele/hvac_group/releases/tag/0.2.0-beta.1) version you could try (but you have to enable beta versions in HACS).

This issue was most likely fixed in #62 but please reopen it if it's not.
